---
- name: Create pihole container
  community.docker.docker_container:
    name: pihole
    image: pihole/pihole:latest
    pull: true
    state: started
    restart_policy: unless-stopped
    env:
      TZ: "{{ timezone }}"
      WEBPASSWORD: "{{ pihole_webpassword }}"
      DNSMASQ_LISTENING: "all"
      PIHOLE_INTERFACE: "{{ pihole_interface }}"
      WEB_PORT: "8081"
      DEFAULT_HOST: "pihole.{{ domain }}"
    volumes:
      - "{{ docker_dir }}/pihole/etc:/etc/pihole"
      - "{{ docker_dir }}/pihole/etc-dnsmasq.d:/etc/dnsmasq.d"
    privileged: true
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      - name: homelab
    labels:
      traefik.enable: "true"
      traefik.http.routers.pihole.entrypoints: "http"
      traefik.http.routers.pihole.rule: "Host(`pihole.{{ domain }}`)"
      traefik.http.middlewares.pihole-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.pihole.middlewares: "pihole-https-redirect"
      traefik.http.routers.pihole-secure.entrypoints: "https"
      traefik.http.routers.pihole-secure.rule: "Host(`pihole.{{ domain }}`)"
      traefik.http.routers.pihole-secure.tls: "true"
      traefik.http.middlewares.pihole-secure.addprefix.prefix: "/admin"
      traefik.http.routers.pihole-secure.service: "pihole"
      traefik.http.services.pihole.loadbalancer.server.port: "8081"
      traefik.docker.network: "homelab"
      com.centurylinklabs.watchtower.enable: "true"