---
- name: Create unmanic container
  community.docker.docker_container:
    name: unmanic
    image: josh5/unmanic:latest
    pull: true
    state: started
    restart_policy: unless-stopped
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
    volumes:
      - "{{ docker_dir }}/unmanic/config:/config"
      - "{{ data_dir }}/media/movies:/library/movies"
      - "{{ data_dir }}/media/tv:/library/tv"
      - /tmp:/tmp/unmanic
    networks:
      - name: homelab
    labels:
      traefik.enable: "true"
      traefik.http.routers.unmanic.entrypoints: "http"
      traefik.http.routers.unmanic.rule: "Host(`unmanic.{{ domain }}`)"
      traefik.http.middlewares.unmanic-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.unmanic.middlewares: "unmanic-https-redirect"
      traefik.http.routers.unmanic-secure.entrypoints: "https"
      traefik.http.routers.unmanic-secure.rule: "Host(`unmanic.{{ domain }}`)"
      traefik.http.routers.unmanic-secure.tls: "true"
      traefik.http.routers.unmanic-secure.service: "unmanic"
      traefik.http.routers.unmanic-secure.middlewares: "authelia@docker"
      traefik.http.services.unmanic.loadbalancer.server.port: "8888"
      traefik.docker.network: "homelab"
      com.centurylinklabs.watchtower.enable: "true"
